### ISSUE TITLE
If media is present, give the functionallity to share a link wich does have proper embed support on third platforms

### ISSUE THREAD

**Issue by Artemixed** [Pixmi/twitter-plus#1]
Hey, I've just stumbled upon your script and I think it's quite good so far. It has its limits, but twitter is too bipolar for a side project to keep up these days.  

My proposal would be to give users the abbility to share media within the suite while maintaining good embeds. 

var reggex = new RegExp("^(http|https)://", "i");
let URL = "URL"; #not sure if this works on the x domain at all, I dont think so fxx seems too good to be true
var match = re.test(URL);` 

function(match) {
 #do le epic fuse match (sorry for not working it out good enough, maintainer)
}

**Comment by Pixmi** [comment]
Hello, I'm not sure if you're hoping for the functionality to work within embedded tweets on other third-party platforms. Unfortunately, that might not be achievable because there's no element present in embedded tweets that can trigger the operation of an observer.

However, if you directly open the images of tweets in a new tab, the conversion will take place as long as the image follows the **twimg.com** path, If the image path is not from twimg.com, please report it to let me know.

I hope this answers your question.

**Comment by Artemixed** [comment]
I've been tinkering with it before submitting a issue and indeed the divs keeps varying. I did saw some chrome extensions managing to pull it off. Im wondering how [they](https://chromewebstore.google.com/detail/fx-twitter-link-replacer/jkmogfahhmpmnbnfailkehfcgpflhnaf?hl=en-GB) pull it off? 

there is offcourse the og lib but that's too big I think https://github.com/FixTweet/FixTweet

**Comment by Artemixed** [comment]
#https://gist.github.com/Atulin/b6a5975ac4f260d16496a2b519f6a698 seems like a possible script, merge worthy

**Comment by Pixmi** [comment]
Browser plugins can invoke APIs to fetch images that are loaded on the page, whether they are static or dynamic. They can then modify the path of the images. While achieving the same result is possible with userscripts, it requires writing scripts for each different website, which is not practical.

My script essentially fulfills my personal needs, so I only intend for it to operate within the Twitter website. However, you can use my script as a template to write a script that suits your own needs.
